nodes:
    core: [ 1, 2, 3, 4, 5, 6 ]
    access: [ 7, 8, 10, 11 ]

networks:
    core: [ [ 1, 2 ], [ 1, 3 ], [ 2, 4 ], [ 3, 4 ],[ 3, 5 ],[ 4, 6 ],[ 5,6 ] ]
    access: [ [ 1, 11 ], [ 3, 8 ], [ 3, 7 ], [ 4, 10 ], [ 5, 7 ], [ 8, 11 ] ]

settings:
    host_prefix: xr-
    config_suffix: .cfg
    global_template: True
    output_path: ./